import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:health_healing/theme/theme.dart'; // Assuming theme is defined here
import 'package:health_healing/firebase_options.dart'; // Generated by FlutterFire

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Health Healing',
      theme: AppTheme.lightTheme, // Apply the custom theme
      home: Scaffold(body: Center(child: Text("Hello Test"))), // Simplified for debugging
      debugShowCheckedModeBanner: false,
    );
  }
}

