import 'package:flutter/material.dart';
import 'package:health_healing/models/health_issue.dart';
import 'package:health_healing/services/health_issue_service.dart';
import 'package:health_healing/models/health_issue_update.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';

class AddHealthIssueUpdateScreen extends StatefulWidget {
  final HealthIssue healthIssue;

  const AddHealthIssueUpdateScreen({super.key, required this.healthIssue});

  @override
  State<AddHealthIssueUpdateScreen> createState() => _AddHealthIssueUpdateScreenState();
}

class _AddHealthIssueUpdateScreenState extends State<AddHealthIssueUpdateScreen> {
  final _formKey = GlobalKey<FormState>();
  final _updateTextController = TextEditingController();
  final HealthIssueService _healthIssueService = HealthIssueService();
  bool _isLoading = false;

  @override
  void dispose() {
    _updateTextController.dispose();
    super.dispose();
  }

  Future<void> _submitUpdate() async {
    if (_formKey.currentState!.validate()) {
      setState(() {
        _isLoading = true;
      });

      final user = FirebaseAuth.instance.currentUser;
      if (user == null) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Error: You must be logged in to add an update.')),
          );
          setState(() {
            _isLoading = false;
          });
        }
        return;
      }

      // Corrected: HealthIssueUpdate constructor only takes updateText, updateDate, and optional files.
      // The id is generated by Firestore. healthIssueId and userId are contextual for the service.
      final newUpdate = HealthIssueUpdate(
        updateText: _updateTextController.text.trim(),
        updateDate: Timestamp.now(),
        files: [], // File uploads for updates can be a future enhancement if needed
      );

      try {
        // The service method addHealthIssueUpdate needs healthIssueId and the update object.
        // It can internally handle associating the userId if needed when saving to Firestore.
        await _healthIssueService.addHealthIssueUpdate(widget.healthIssue.id!, newUpdate, user.uid);
        if (mounted) {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(content: Text('Update added successfully!')),
            );
            Navigator.pop(context, true); // Return true to indicate success
        }
      } catch (e) {
        if (mounted) {
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(content: Text('Failed to add update: ${e.toString()}')),
            );
        }
      } finally {
        if (mounted) {
            setState(() {
                _isLoading = false;
            });
        }
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Add Update'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: <Widget>[
              Text(
                'Add an update for: ${widget.healthIssue.issueName}',
                style: Theme.of(context).textTheme.titleMedium,
              ),
              const SizedBox(height: 20),
              TextFormField(
                controller: _updateTextController,
                decoration: const InputDecoration(
                  labelText: 'Update Details',
                  hintText: 'Enter your update, notes, or observations...',
                  border: OutlineInputBorder(),
                ),
                maxLines: 5,
                validator: (value) {
                  if (value == null || value.trim().isEmpty) {
                    return 'Please enter some details for the update.';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 24.0),
              _isLoading
                  ? const Center(child: CircularProgressIndicator())
                  : ElevatedButton(
                      onPressed: _submitUpdate,
                      style: ElevatedButton.styleFrom(
                        padding: const EdgeInsets.symmetric(vertical: 16.0)
                      ),
                      child: const Text('Save Update'),
                    ),
            ],
          ),
        ),
      ),
    );
  }
}

